In [1]:
import oandapyV20
import oandapyV20.endpoints.instruments as instruments
import pandas as pd
from datetime import datetime, timedelta
import time
import oandapyV20
import oandapyV20.endpoints.instruments as instruments

In [2]:

# OANDA API credentials
api_token = '4774a622bc314440290f530efcc46453-eb96728988593ba944d5285fbcf8786a'
account_id = '101-001-8028197-001'

# OANDA API connection
api = oandapyV20.API(access_token=api_token)

In [3]:
# Download Data for Backtest 
client = oandapyV20.API(access_token=api_token)

# Get historical data for EURUSD
instrument = "EUR_USD"
start_date = "2020-11-01"
end_date = "2023-10-03"
params = {"from": start_date, "to": end_date, "granularity": "D"}
r = instruments.InstrumentsCandles(instrument=instrument, params=params)
candles = client.request(r)["candles"]

# Create a DataFrame from the historical data
df = pd.DataFrame([{"time": c["time"], "open": c["mid"]["o"], "high": c["mid"]["h"], "low": c["mid"]["l"], "close": c["mid"]["c"]} for c in candles])
df["time"] = pd.to_datetime(df["time"])
df.set_index("time", inplace=True)

display(df)

                              open     high      low    close
time
2020-11-01 22:00:00+00:00  1.16501  1.16558  1.16222  1.16404
2020-11-02 22:00:00+00:00  1.16387  1.17399  1.16236  1.17196
2020-11-03 22:00:00+00:00  1.17178  1.17707  1.16027  1.17226
2020-11-04 22:00:00+00:00  1.17226  1.18598  1.17109  1.18284
2020-11-05 22:00:00+00:00  1.18254  1.18910  1.17954  1.18737
...                            ...      ...      ...      ...
2023-09-26 21:00:00+00:00  1.05698  1.05743  1.04880  1.05026
2023-09-27 21:00:00+00:00  1.05074  1.05790  1.04911  1.05664
2023-09-28 21:00:00+00:00  1.05616  1.06171  1.05581  1.05744
2023-10-01 21:00:00+00:00  1.05720  1.05919  1.04779  1.04780
2023-10-02 21:00:00+00:00  1.04788  1.04936  1.04485  1.04669

[759 rows x 4 columns]