# CME NQ 100 Emini Pivot Calculator

by Wolfrank Guzman
#
GitHub: @guzmanwolfrank

In [202]:
import yfinance as yf
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd



# Ticker
ticker = 'NQ=F'

# Download data for the last 30 days with daily intervals
ndata = yf.download(ticker, period="30d", interval="1d")

# Display the downloaded data
#display(ndata)

# Extract high, low, close, and open prices and round them to 2 decimal places
high = ndata['High'].round(2)
low = ndata['Low'].round(2)
close = ndata['Close'].round(2)
open_price = ndata['Open'].round(2)

# Calculate the pivot point and support/resistance levels
pivot_point = (high + low + close) / 3
support1 = (2 * pivot_point) - high
support2 = pivot_point - (high - low)
support3 = low - 2 * (high - pivot_point)
resistance1 = (2 * pivot_point) - low
resistance2 = pivot_point + (high - low)
resistance3 = high + 2 * (pivot_point - low)

# Create a DataFrame with the calculated values
pivot_data = pd.DataFrame({
    'High': high,
    'Low': low,
    'Close': close,
    'Open': open_price,
  
    'R3': resistance3,
    'R2': resistance2,
    'R1': resistance1,

    'Pivot_Point': pivot_point,
  
    'S1': support1,
    'S2': support2,
    'S3': support3,
   
}).round(2)

# Display the DataFrame with calculated values
# Display(pivot_data)
df_except_last_row = pivot_data.iloc[:-1]
Pivdata= df_except_last_row


dpiv = (Pivdata.iloc[-1])

display(dpiv)

display(Pivdata)

[*********************100%***********************]  1 of 1 completed

High           17752.00
Low            17542.00
Close          17634.50
Open           17614.75
R3             17953.67
R2             17852.83
R1             17743.67
Pivot_Point    17642.83
S1             17533.67
S2             17432.83
S3             17323.67
Name: 2024-01-25 00:00:00, dtype: float64

,High,Low,Close,Open,R3,R2,R1,Pivot_Point,S1,S2,S3
Date,,,,,,,,,,,
2023-12-21,16970.25,16790.25,16956.50,16790.25,17201.08,17085.67,17021.08,16905.67,16841.08,16725.67,16661.08
2023-12-22,17041.50,16891.50,16980.00,16956.00,17200.50,17121.00,17050.50,16971.00,16900.50,16821.00,16750.50
2023-12-26,17111.25,16964.50,17083.50,16964.50,17288.42,17199.83,17141.67,17053.08,16994.92,16906.33,16848.17
2023-12-27,17133.00,17055.50,17113.25,17090.25,17223.17,17178.08,17145.67,17100.58,17068.17,17023.08,16990.67
2023-12-28,17165.25,17077.75,17090.50,17127.00,17232.08,17198.67,17144.58,17111.17,17057.08,17023.67,16969.58
2023-12-29,17131.00,16938.25,17023.50,17090.25,17316.33,17223.67,17123.58,17030.92,16930.83,16838.17,16738.08
2024-01-02,17038.50,16622.50,16720.00,17019.00,17380.83,17209.67,16964.83,16793.67,16548.83,16377.67,16132.83
2024-01-03,16737.25,16522.00,16538.00,16736.75,16891.42,16814.33,16676.17,16599.08,16460.92,16383.83,16245.67
2024-01-04,16587.25,16436.00,16445.00,16545.25,16694.08,16640.67,16542.83,16489.42,16391.58,16338.17,16240.33
2024-01-05,16577.25,16334.25,16460.25,16455.00,16823.25,16700.25,16580.25,16457.25,16337.25,16214.25,16094.25
2024-01-08,16811.25,16378.25,16803.75,16470.00,17383.58,17097.42,16950.58,16664.42,16517.58,16231.42,16084.58
2024-01-09,16868.50,16657.75,16830.25,16788.00,17124.00,16996.25,16913.25,16785.50,16702.50,16574.75,16491.75
2024-01-10,16983.00,16801.50,16945.25,16829.50,17199.83,17091.42,17018.33,16909.92,16836.83,16728.42,16655.33
2024-01-11,17057.00,16753.00,16966.25,16955.00,17401.83,17229.42,17097.83,16925.42,16793.83,16621.42,16489.83
2024-01-12,17042.50,16866.50,16969.25,16957.75,17228.33,17135.42,17052.33,16959.42,16876.33,16783.42,16700.33
2024-01-15,17024.25,16936.25,16970.00,16961.75,17105.42,17064.83,17017.42,16976.83,16929.42,16888.83,16841.42
2024-01-16,17033.75,16811.75,16966.50,16961.75,17284.92,17159.33,17062.92,16937.33,16840.92,16715.33,16618.92
2024-01-17,16982.00,16689.25,16869.75,16978.00,17297.50,17139.75,17004.75,16847.00,16712.00,16554.25,16419.25
2024-01-18,17125.75,16834.25,17110.00,16854.50,17503.92,17314.83,17212.42,17023.33,16920.92,16731.83,16629.42
2024-01-19,17471.25,17107.25,17438.50,17116.00,17934.75,17703.00,17570.75,17339.00,17206.75,16975.00,16842.75
2024-01-22,17585.00,17434.00,17458.50,17466.00,17702.00,17643.50,17551.00,17492.50,17400.00,17341.50,17249.00
2024-01-23,17558.25,17409.50,17531.25,17461.00,17738.58,17648.42,17589.83,17499.67,17441.08,17350.92,17292.33
2024-01-24,17793.50,17552.25,17621.00,17554.00,18000.17,17896.83,17758.92,17655.58,17517.67,17414.33,17276.42
2024-01-25,17752.00,17542.00,17634.50,17614.75,17953.67,17852.83,17743.67,17642.83,17533.67,17432.83,17323.67